# Generated by Django 5.2.6 on 2025-10-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0002_subtotalcarrito'),
        ('productos', '0003_alter_producto_imagen'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Compra',
        ),
    ]
