# Generated by Django 5.2.6 on 2025-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0006_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='compras',
            field=models.ManyToManyField(blank=True, related_name='carritos', to='AppCarrito.compra'),
        ),
    ]
