# Generated by Django 5.2.6 on 2025-10-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0007_alter_carrito_compras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtotalcarrito',
            options={'verbose_name': 'Subtotal Carrito'},
        ),
    ]
