# Generated by Django 5.2.6 on 2025-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0008_alter_subtotalcarrito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtotalcarrito',
            options={'verbose_name': 'Subtotal Carrito', 'verbose_name_plural': 'Subtotales Carrito'},
        ),
    ]
