# Generated by Django 5.2.6 on 2025-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0009_alter_subtotalcarrito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtotalcarrito',
            name='compras',
            field=models.ManyToManyField(blank=True, to='AppCarrito.compra'),
        ),
    ]
