# Generated by Django 5.2.6 on 2025-10-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0010_subtotalcarrito_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios_x_compras',
        ),
    ]
