# Generated by Django 5.2.6 on 2025-10-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0012_alter_compra_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='subtotal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarrito.subtotalcarrito'),
        ),
    ]
