# Generated by Django 5.2.6 on 2025-10-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0013_carrito_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='subtotal',
        ),
    ]
