# Generated by Django 5.2.7 on 2025-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0014_remove_carrito_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad_total_productos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
