# Generated by Django 5.2.7 on 2025-10-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0015_carrito_cantidad_total_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_total_productos',
        ),
    ]
