# Generated by Django 5.2.6 on 2025-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0005_alter_compra_usuario_comprador_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compras',
            field=models.ManyToManyField(blank=True, to='AppCarrito.compra'),
        ),
    ]
