# Generated by Django 5.2.7 on 2025-10-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
