[project]
name = "yerba-mate-origen-clon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "pillow>=11.3.0",
]
