# Generated by Django 5.2.7 on 2025-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion larga'),
        ),
    ]
